### ISSUE TITLE
[Bug]: Execution time increased by package count stat

### ISSUE THREAD

**Issue by yuki-was-taken** [iinsertNameHere/catnip#94]
### What version of Catnip are you running?
Commit a7eecc7a3950bdcbb803e306b8a1f68bc1450051

### Describe the bug:
Usually, Catnip on my system executes in 0.014 seconds. However, once 6eabc9623da3c4b5d9b20b0dbece168dba96c2bf was merged, the execution time increases to a hefty 0.509 seconds. This is because it takes some time to get the package count. *However*, once I disable the package count stat by commenting it out in the `config.toml`, the execution time is still the same, at 0.508 seconds.

### Screenshots:
Nil.

### Device:
 - OS: Alpine Linux
 - DE/WM: dwm
 - TERMINAL: st

### Additional context:
I believe that even though the stat is commented out, Catnip still gets the value of the stat and just doesn't display it. Could Catnip be changed so that it doesn't grab the values of the stats that are commented out? This will decrease the execution time.

**Comment by iinsertNameHere** [comment]
Yes, you are right. Catnip Always geht's all stats, even If they are Not displayed. I think this could be fixed as follows:

Instead of executing the probe Funktions inside of the fetch proc, IT would be better to Just execute IT inside of the Render funktioniert so that only the stats that are shown on Screen will be fetched.

**Comment by iinsertNameHere** [comment]
Should work @yuki-was-taken

**Comment by yuki-was-taken** [comment]
Thank you, it does.
